In [1]:
import numpy as np
import pandas as pd
from sklearn.linear_model import LinearRegression

## Read Data

In [34]:
df_spencer = pd.read_excel('/Users/apple/Documents/Study/MMA 2022S/841 - Supply Chain/om-0549x.xlsx', sheet_name = 'Exhibit 4 Spencer')

In [35]:
df_william = pd.read_excel('/Users/apple/Documents/Study/MMA 2022S/841 - Supply Chain/om-0549x.xlsx', sheet_name = 'Exhbit 4 Williams')

In [36]:
df_spencer.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 70 entries, 0 to 69
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   Miles   70 non-null     int64  
 1   Stops   70 non-null     int64  
 2   Hours   70 non-null     float64
dtypes: float64(1), int64(2)
memory usage: 1.8 KB


In [37]:
df_william.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 61 entries, 0 to 60
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   Miles   61 non-null     int64  
 1   Stops   61 non-null     int64  
 2   Hours   61 non-null     float64
dtypes: float64(1), int64(2)
memory usage: 1.6 KB


## Linear Regression

In [38]:
regressor_spencer = LinearRegression()
regressor_spencer.fit(df_spencer.iloc[:,0:2], df_spencer.iloc[:,2:])

LinearRegression()

In [39]:
print(regressor_spencer.intercept_)
print(regressor_spencer.coef_)

[3.00367032]
[[0.01801524 0.30845476]]


In [42]:
regressor_william = LinearRegression()
regressor_william.fit(df_william.iloc[:,0:2], df_william.iloc[:,2:])

LinearRegression()

In [43]:
print(regressor_william.intercept_)
print(regressor_william.coef_)

[4.44783567]
[[0.01551258 0.33864432]]


## Testing data

In [28]:
X = pd.DataFrame({'Miles': [200, 250,300, 100], 'Stops': [2,3,4,2]})

In [29]:
X

Miles  Stops
0    200      2
1    250      3
2    300      4
3    100      2

### Check what time will William or Spencer take for the testing dataset

In [44]:
regressor_william.predict(X)

array([[ 8.22764034],
       [ 9.34191366],
       [10.45618699],
       [ 6.67638232]])

In [45]:
regressor_spencer.predict(X)

array([[7.22362796],
       [8.43284475],
       [9.64206154],
       [5.4221039 ]])

> Now we see that for the same distance and stops, William takes more time than spencer

## Recommendations

> Change the compensation structure to take into consideration the number of miles travelled - regardles -It will remove the aspects that introduce variation in the processes 